# Generated by Django 4.1.2 on 2022-12-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommatesgroup',
            options={'ordering': ('id',), 'verbose_name': 'группа человек', 'verbose_name_plural': 'группы человек'},
        ),
        migrations.AlterField(
            model_name='user',
            name='roommates_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.roommatesgroup', verbose_name='группа человек'),
        ),
    ]
