# Generated by Django 4.1.2 on 2022-11-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_accounting', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roommates_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods_accounting.roommatesgroup', verbose_name='группа человек'),
        ),
    ]
