# Generated by Django 4.1.2 on 2022-12-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_roommatesgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roommates_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.roommatesgroup', verbose_name='группа человек'),
        ),
    ]
