# Generated by Django 4.1.2 on 2022-11-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'категория продукта', 'verbose_name_plural': 'категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productpurchase',
            options={'verbose_name': 'покупка товара', 'verbose_name_plural': 'покупки товаров'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'покупка', 'verbose_name_plural': 'покупки'},
        ),
        migrations.AlterModelOptions(
            name='roommatesgroup',
            options={'verbose_name': 'группа человек', 'verbose_name_plural': 'группы человек'},
        ),
        migrations.RemoveField(
            model_name='roommatesgroup',
            name='user',
        ),
    ]
