# Generated by Django 4.1.2 on 2022-12-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpurchase',
            options={'ordering': ('-id',), 'verbose_name': 'покупка товара', 'verbose_name_plural': 'покупки товаров'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('id',), 'verbose_name': 'покупка', 'verbose_name_plural': 'покупки'},
        ),
    ]
